export const TEMPORAL_MODULE_OPTIONS = 'TEMPORAL_MODULE_OPTIONS';
export const TEMPORAL_CLIENT = 'TEMPORAL_CLIENT';
export const TEMPORAL_WORKER = 'TEMPORAL_WORKER';
export const TEMPORAL_OPTIONS_TYPE = 'TEMPORAL_OPTIONS_TYPE';
export const TEMPORAL_ASYNC_OPTIONS_TYPE = 'TEMPORAL_ASYNC_OPTIONS_TYPE';
