export const TEMPORAL_ACTIVITY = Symbol('TEMPORAL_ACTIVITY');
export const TEMPORAL_ACTIVITY_METHOD = Symbol('TEMPORAL_ACTIVITY_METHOD');
export const TEMPORAL_WORKFLOW = Symbol('TEMPORAL_WORKFLOW');
export const TEMPORAL_CLIENT = Symbol('TEMPORAL_CLIENT');
export const TEMPORAL_MODULE_OPTIONS = Symbol('TEMPORAL_MODULE_OPTIONS');
